### ISSUE TITLE
Course progress overview

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-teacher-tools#10]
This view should be useful to quickly answer a few questions:
*  ¿Are my students practising? 
* ¿How is X student going? ¿Has he/she completed all the guides?

**Comment by flbulgarelli** [comment]
There are a fiew metrics/queries I would like to have:

* which is the furthest exercise in a guide any students has reached. 
* which percentage of students have reached a given exercise. For example: I would like to know the rate of students that reached fifth exercise within a guide. 
* which students have not reached a given exercise yet.  
* which students have resolved a given exercise

Here, when I say **reached** X I mean: the students has resolved X-1, regardless whether she has skipped some exercises or not. 

All those metrics are interesting when I want to know If I am able to continue with some explanation or wrap up that requires having reached some point in the guide.

**Comment by faloi** [comment]
That's great, but not related to this issue. Moving it to #12
