### ISSUE TITLE
Hide unsolved exercises

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-teacher-tools#18]
Having the exercise name and a grey circle  doesn't give any information and wastes valuable space.

**Comment by faloi** [comment]
@flbulgarelli @aguspina (and perhaps @logain) I need an opinion here. Hiding the exercises seems like a good idea to me, but a side effect is that each card has a different height and they look messy with the current layout:

![image](https://cloud.githubusercontent.com/assets/1585835/10239442/c189fea4-68a3-11e5-9dbd-4478df6b27f8.png)

How can we redesign this? My first idea was using a table, but it should have too many columns... and a table is rarely the best way to show information (just the simplest to program).

**Comment by aguspina** [comment]
I actually don't know how to fix it. Perhaps a designer's opinion could be
better. @nepgroup

**Comment by flbulgarelli** [comment]
Hmm, personally I don't like the whole idea of this issue - hiding unsolved exercises - , because they make information not comparable. And this is just a consequence of it.

**Comment by nepgroup** [comment]
In this case we have two options, the first option is to migrate this section to "material design" using cards that are dynamic in their position, the second option is to maintain this structure with a height fixed, but the list of exercises to apply a "max-height" which activate a scroll for the rest of the exercises.

**Comment by faloi** [comment]
I thought of that, something similar to Google Keep where the notes fit the
board according their size.

But I don't know how to do that nor a keyword to search. I'll give
"material design" a try, perhaps I find something.

**Comment by aguspina** [comment]
@faloi is a fix height with an overflow css property
